# Generated by Django 4.0.3 on 2022-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Others', 'others')], max_length=6)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('class_name', models.CharField(choices=[('csa', 'CSA'), ('csb', 'CSB'), ('eca', 'ECA'), ('ecb', 'ECB'), ('eee', 'EEE'), ('mech', 'MECH'), ('eb', 'EB')], max_length=4)),
                ('batch', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('last_donated_date', models.DateField()),
                ('diseases', models.CharField(max_length=1000)),
                ('allergies', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('cardiac', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('bleeding_disorders', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hiv', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hepatitis', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
            ],
        ),
    ]
