# Generated by Django 4.0.3 on 2022-12-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbankdonor',
            old_name='quantity_needed',
            new_name='quantity_available',
        ),
    ]
